import 'dart:io';
import 'dart:convert';

void main() async {
  final enFile = File(r'c:\Users\Y\OneDrive\Desktop\FYP_MOBILE\mobile_app\lib\l10n\app_en.arb');
  final amFile = File(r'c:\Users\Y\OneDrive\Desktop\FYP_MOBILE\mobile_app\lib\l10n\app_am.arb');

  final enAdditions = {
    "provReject": "Reject",
    "provAccept": "Accept",
    "provMarkCompleted": "Mark as Completed",
    "provNoPayment": "Could not launch payment screen",
    "provDashboard": "Provider Dashboard",
    "provNoStats": "No stats available",
    "provAddNewService": "Add New Service",
    "provDashboardTab": "Dashboard",
    "provMyServices": "My Services",
    "provBookings": "Bookings",
    "provMessages": "Messages",
    "provReviews": "Reviews",
    "provSubHistory": "Subscription History",
    "provProfileSettings": "Profile Settings",
    "provSubmitComplaint": "Submit Complaint",
    "provRatePlatform": "Rate Platform",
    "provLogout": "Logout",
    "provProfileUpdated": "Profile updated successfully",
    "provEditProfile": "Edit Profile",
    "provSaveChanges": "Save Changes",
    "provCustomerReviews": "Customer Reviews",
    "provSeeCustomersSaying": "See what your customers are saying about your services",
    "provRecentFeedback": "Recent Feedback",
    "provSortNewest": "Sort: Newest First",
    "provNoReviews": "No reviews yet.",
    "provOverallRating": "Overall Rating",
    "provBooked": "Booked:",
    "provNoServices": "No services found.",
    "provAddService": "Add a Service",
    "provEditService": "Edit Service",
    "provNoSubPayments": "No subscription payments found.",
    "provSelectCategory": "Please select a category",
    "provServiceUpdated": "Service updated successfully",
    "provServiceCreated": "Service created successfully",
    "adminBookingMgmt": "Booking Management",
    "adminRetry": "Retry",
    "adminNoBookings": "No bookings found.",
    "adminAddNewCat": "Add New Category",
    "adminCancel": "Cancel",
    "adminCatCreated": "Category created!",
    "adminAdd": "Add",
    "adminManageCat": "Manage Categories",
    "adminNoCategories": "No categories found.",
    "adminNoProvidersInCat": "No providers found in this category.",
    "adminReplySent": "Reply sent!",
    "adminSendReply": "Send Reply",
    "adminComplaints": "Complaints",
    "adminNoComplaints": "No complaints found.",
    "adminAdminReply": "Admin Reply:",
    "adminReplyResolve": "Reply & Resolve",
    "adminDashboard": "Admin Dashboard",
    "adminPlatformOverview": "Platform Overview",
    "adminTotalRevenue": "Total Platform Revenue",
    "adminQuickMgmt": "Quick Management",
    "adminReviewComplaints": "Review Complaints",
    "adminCategories": "Categories",
    "adminUserMgmt": "User Management",
    "adminSubscriptions": "Subscriptions",
    "adminVerification": "Verification",
    "adminSubsRevenue": "Subscriptions & Revenue",
    "adminRecentPayments": "Recent Payments",
    "adminUserDocs": "User Documents",
    "adminEduDocs": "Educational Documents",
    "adminNoDocs": "No documents uploaded for this user.",
    "adminDownload": "Download",
    "adminNoUsers": "No users found.",
    "adminProvApproved": "Provider approved successfully",
    "adminRejectProv": "Reject Provider",
    "adminProvRejected": "Provider rejected",
    "adminProvVerifications": "Provider Verifications",
    "adminNoPendingVerifs": "No pending verifications.",
    "adminIdentityDocs": "Identity Documents",
    "adminApprove": "Approve",
    "adminPdfDoc": "PDF Document",
    "adminExternal": "External",
    "adminFailedImage": "Failed to load image",
    "custProfileUpdated": "Profile updated successfully!",
    "custNotifications": "Notifications",
    "custNotificationsComingSoon": "Notifications screen coming soon!",
    "custSaved": "Saved",
    "custSavedComingSoon": "Saved screen coming soon!",
    "chatMessageFailed": "Your message couldn't be sent. Please check your connection.",
    "chatMessagingEnabledWait": "Messaging will be enabled once the provider accepts your request.",
    "chatSecureMessaging": "Secure Messaging",
    "chatNoMessages": "No messages to show yet",
    "compHistory": "Complaint History",
    "compAdminResponse": "Admin Response",
    "compSubmitted": "Complaint submitted successfully. We will review it soon.",
    "compReport": "Report a Complaint",
    "compHelpImprove": "Help us improve",
    "compProvideDetails": "Please provide details about your issue. We take all complaints seriously.",
    "compLow": "Low",
    "compMedium": "Medium",
    "compHigh": "High",
    "widgetThanksFeedback": "Thank you for your feedback!",
    "widgetRatePlatform": "Rate the platform",
    "widgetHowIsExperience": "How is your experience with QuickServe so far?",
    "widgetSubmitFeedback": "Submit Feedback",
    "widgetTopRated": "Top Rated Professionals"
  };

  final amAdditions = {
    "provReject": "አትቀበል",
    "provAccept": "ተቀበል",
    "provMarkCompleted": "እንደተጠናቀቀ ምልክት አድርግ",
    "provNoPayment": "የክፍያ ማያ ገጽ መክፈት አልተቻለም",
    "provDashboard": "የአቅራቢ ዳሽቦርድ",
    "provNoStats": "ምንም ስታቲስቲክስ የለም",
    "provAddNewService": "አዲስ አገልግሎት ያክሉ",
    "provDashboardTab": "ዳሽቦርድ",
    "provMyServices": "የእኔ አገልግሎቶች",
    "provBookings": "ምዝገባዎች",
    "provMessages": "መልዕክቶች",
    "provReviews": "ግምገማዎች",
    "provSubHistory": "የደንበኝነት ምዝገባ ታሪክ",
    "provProfileSettings": "የመገለጫ ቅንብሮች",
    "provSubmitComplaint": "ቅሬታ ያቅርቡ",
    "provRatePlatform": "መድረኩን ደረጃ ይስጡ",
    "provLogout": "ውጣ",
    "provProfileUpdated": "መገለጫው በተሳካ ሁኔታ ተዘምኗል",
    "provEditProfile": "መገለጫ ያርትዑ",
    "provSaveChanges": "ለውጦችን ያስቀምጡ",
    "provCustomerReviews": "የደንበኛ ግምገማዎች",
    "provSeeCustomersSaying": "ደንበኞችዎ ስለ አገልግሎቶችዎ ምን እንደሚሉ ይመልከቱ",
    "provRecentFeedback": "የቅርብ ጊዜ አስተያየት",
    "provSortNewest": "ደርድር: አዲሱ መጀመሪያ",
    "provNoReviews": "ምንም ግምገማዎች የሉም።",
    "provOverallRating": "አጠቃላይ ደረጃ",
    "provBooked": "የተያዘ:",
    "provNoServices": "ምንም አገልግሎቶች አልተገኙም።",
    "provAddService": "አገልግሎት ያክሉ",
    "provEditService": "አገልግሎት ያርትዑ",
    "provNoSubPayments": "ምንም የደንበኝነት ምዝገባ ክፍያዎች አልተገኙም።",
    "provSelectCategory": "እባክዎ ምድብ ይምረጡ",
    "provServiceUpdated": "አገልግሎት በተሳካ ሁኔታ ተዘምኗል",
    "provServiceCreated": "አገልግሎት በተሳካ ሁኔታ ተፈጥሯል",
    "adminBookingMgmt": "የምዝገባ አስተዳደር",
    "adminRetry": "እንደገና ይሞክሩ",
    "adminNoBookings": "ምንም የተያዙ ቦታዎች አልተገኙም።",
    "adminAddNewCat": "አዲስ ምድብ ያክሉ",
    "adminCancel": "ሰርዝ",
    "adminCatCreated": "ምድብ ተፈጥሯል!",
    "adminAdd": "አክል",
    "adminManageCat": "ምድቦችን ያስተዳድሩ",
    "adminNoCategories": "ምንም ምድቦች አልተገኙም።",
    "adminNoProvidersInCat": "በዚህ ምድብ ውስጥ ምንም አቅራቢዎች አልተገኙም።",
    "adminReplySent": "ምላሽ ተልኳል!",
    "adminSendReply": "ምላሽ ይላኩ",
    "adminComplaints": "ቅሬታዎች",
    "adminNoComplaints": "ምንም ቅሬታዎች አልተገኙም።",
    "adminAdminReply": "የአስተዳዳሪ ምላሽ:",
    "adminReplyResolve": "ምላሽ ይስጡ እና ይፍቱ",
    "adminDashboard": "የአስተዳዳሪ ዳሽቦርድ",
    "adminPlatformOverview": "የመድረክ አጠቃላይ እይታ",
    "adminTotalRevenue": "አጠቃላይ የመድረክ ገቢ",
    "adminQuickMgmt": "ፈጣን አስተዳደር",
    "adminReviewComplaints": "ቅሬታዎችን ይገምግሙ",
    "adminCategories": "ምድቦች",
    "adminUserMgmt": "የተጠቃሚ አስተዳደር",
    "adminSubscriptions": "የደንበኝነት ምዝገባዎች",
    "adminVerification": "ማረጋገጫ",
    "adminSubsRevenue": "የደንበኝነት ምዝገባዎች እና ገቢ",
    "adminRecentPayments": "የቅርብ ጊዜ ክፍያዎች",
    "adminUserDocs": "የተጠቃሚ ሰነዶች",
    "adminEduDocs": "የትምህርት ሰነዶች",
    "adminNoDocs": "ለዚህ ተጠቃሚ የተሰቀሉ ሰነዶች የሉም።",
    "adminDownload": "አውርድ",
    "adminNoUsers": "ምንም ተጠቃሚዎች አልተገኙም።",
    "adminProvApproved": "አቅራቢው በተሳካ ሁኔታ ጸድቋል",
    "adminRejectProv": "አቅራቢን ውድቅ አድርግ",
    "adminProvRejected": "አቅራቢ ውድቅ ተደርጓል",
    "adminProvVerifications": "የአቅራቢ ማረጋገጫዎች",
    "adminNoPendingVerifs": "በመጠባበቅ ላይ ያሉ ማረጋገጫዎች የሉም።",
    "adminIdentityDocs": "የማንነት ሰነዶች",
    "adminApprove": "አጽድቅ",
    "adminPdfDoc": "የፒዲኤፍ ሰነድ",
    "adminExternal": "ውጫዊ",
    "adminFailedImage": "ምስል መጫን አልተሳካም",
    "custProfileUpdated": "መገለጫው በተሳካ ሁኔታ ተዘምኗል!",
    "custNotifications": "ማሳወቂያዎች",
    "custNotificationsComingSoon": "የማሳወቂያዎች ማያ ገጽ በቅርቡ ይመጣል!",
    "custSaved": "ተቀምጧል",
    "custSavedComingSoon": "የተቀመጡ ነገሮች ማያ ገጽ በቅርቡ ይመጣል!",
    "chatMessageFailed": "መልዕክትዎ ሊላክ አልቻለም። እባክዎ ግንኙነትዎን ያረጋግጡ።",
    "chatMessagingEnabledWait": "አቅራቢው ጥያቄዎን ከተቀበለ በኋላ መልዕክት መላላክ ይነቃል።",
    "chatSecureMessaging": "ደህንነቱ የተጠበቀ መልዕክት",
    "chatNoMessages": "እስካሁን ምንም መልዕክቶች የሉም",
    "compHistory": "የቅሬታ ታሪክ",
    "compAdminResponse": "የአስተዳዳሪ ምላሽ",
    "compSubmitted": "ቅሬታ በተሳካ ሁኔታ ቀርቧል። በቅርቡ እንገመግመዋለን።",
    "compReport": "ቅሬታ ያቅርቡ",
    "compHelpImprove": "እንድናሻሽል እርዱን",
    "compProvideDetails": "እባክዎ ስለ ጉዳይዎ ዝርዝሮችን ያቅርቡ። ሁሉንም ቅሬታዎች በቁም ነገር እንወስዳለን።",
    "compLow": "ዝቅተኛ",
    "compMedium": "መካከለኛ",
    "compHigh": "ከፍተኛ",
    "widgetThanksFeedback": "ስለ ግብረመልስዎ እናመሰግናለን!",
    "widgetRatePlatform": "መድረኩን ደረጃ ይስጡ",
    "widgetHowIsExperience": "ከኩዊክ ሰርቭ ጋር ያለዎት ተሞክሮ እስካሁን እንዴት ነው?",
    "widgetSubmitFeedback": "ግብረመልስ ያስገቡ",
    "widgetTopRated": "ከፍተኛ ደረጃ የተሰጣቸው ባለሙያዎች"
  };

  void appendToFile(File file, Map<String, String> additions) async {
    final Map<String, dynamic> jsonMap = jsonDecode(await file.readAsString());
    jsonMap.addAll(additions);
    
    // Write back nicely formatted
    final encoder = JsonEncoder.withIndent('  ');
    await file.writeAsString(encoder.convert(jsonMap));
  }

  await appendToFile(enFile, enAdditions);
  await appendToFile(amFile, amAdditions);
  print('Added all remaining keys to arb files.');
}
